USE fo4_char_mgr_db;

INSERT INTO dlc (name)
VALUES ("Base Game"), ("Automatron"), ("Wasteland Workshop"), ("Far Harbor"), ("Contraptions Workshop"), ("Vault-Tec Workshop"), ("Nuka-World");

INSERT INTO perk (name, perk_rank, req_name, req_rank, req_level, effect, dlc_id)
VALUES ("Iron Fist", 1, "Strength", 1, 1, "Channel your chi to unlease devestating fury! Punching attacks do 20% more damage to your opponent.", 1),
("Iron Fist", 2, "Iron Fist", 1, 9, "Punching attacks now do 40% more damage and can disarm your opponent.", 1),
("Iron Fist", 3, "Iron Fist", 2, 18, "Punching attacks now do 60% mroe damage. Unarmed Power Attacks have a chance to cripple one of your opponent's limbs.", 1),
("Iron Fist", 4, "Iron Fist", 3, 31, "Punching attacks now do 80% more damage. Unarmed Power Attacks have an increased chance to cripple one of your opponent's limbs.", 1),
("Iron Fist", 5, "Iron Fist", 4, 46, "Punching attacks now do double damage. Criticals in V.A.T.S. will paralyze your opponent.", 1),
("Big Leagues", 1, "Strength", 2, 1, "Swing for the fences! Do 20% more melee weapon damage.", 1),
("Big Leagues", 2, "Big Leagues", 1, 7, "You now do 40% more melee weapon damage and gain a chance to disarm your opponent.", 1),
("Big Leagues", 3, "Big Leagues", 2, 15, "You now do 60% more melee weapon damage and gain an increased chance to disarm your opponent.", 1),
("Big Leagues", 4, "Big Leagues", 3, 27, "You now do 80% more melee weapon damage and hit all targets in front of you.", 1),
("Big Leagues", 5, "Big Leagues", 4, 42, "You now do double damage with a melee weapon, and gain a chance to cripple your opponent, or grand slam their head clean off!", 1),
("Armorer", 1, "Strength", 3, 1, "Protect yourself from the dangers of the Wasteland with access to base level and Rank 1 armor mods.", 1),
("Armorer", 2, "Armorer", 1, 13, "You gain access to Rank 2 armor mods.", 1),
("Armorer", 3, "Armorer", 2, 25, "You gain access to Rank 3 armor mods.", 1),
("Armorer", 4, "Armorer", 3, 39, "You gain access to Rank 4 armor mods.", 1),
("Blacksmith", 1, "Strength", 4, 1, "Fire up the forge and gain access to base level and Rank 1 melee weapon mods.", 1),
("Blacksmith", 2, "Blacksmith", 1, 16, "You gain access to Rank 2 melee weapon mods.", 1),
("Blacksmith", 3, "Blacksmith", 2, 29, "You gain access to Rank 3 melee weapon mods.", 1),
("Heavy Gunner", 1, "Strength", 5, 1, "Thanks to practice and conditioning, heavy guns do 20% more damage.", 1),
("Heavy Gunner", 2, "Heavy Gunner", 1, 11, "Heavy guns now do 40% more damage, and have improved hip fire accuracy.", 1),
("Heavy Gunner", 3, "Heavy Gunner", 2, 21, "Heavy guns now do 60% more damage. Hip fire accuracy is increased even more.", 1),
("Heavy Gunner", 4, "Heavy Gunner", 3, 35, "Heavy guns now do 80% more damage and have a chance to stagger your opponent.", 1),
("Heavy Gunner", 5, "Heavy Gunner", 4, 47, "Heavy guns now do double damage.", 1),
("Strong Back", 1, "Strength", 6, 1, "What are you, part pack mule? Gain +25 to carry weight.", 1),
("Strong Back", 2, "Strong Back", 1, 10, "You now have +50 to carry weight.", 1),
("Strong Back", 3, "Strong Back", 2, 20, "When overencumbered, you can use Action Points to run.", 1),
("Strong Back", 4, "Strong Back", 3, 30, "When overencumbered, you can fast travel.", 1),
("Strong Back", 5, "Strong Back", 4, 40, "When overencumbered, running costs 50% less action points.", 4),
("Steady Aim", 1, "Strength", 7, 1, "Stay on target! Hip-fire accuracy is improved when firing any gun.", 1),
("Steady Aim", 2, "Steady Aim", 1, 28, "Hip-fire accuracy is improved even more when firing any gun.", 1),
("Steady Aim", 3, "Steady Aim", 2, 49, "Hip-fire damage is improved when firing any gun.", 7),
("Basher", 1, "Strength", 8, 1, "Get up close and personal! Gun bashing does 25% mroe damage.", 1),
("Basher", 2, "Basher", 1, 5, "Gun bashing now does 50% more damage and possibly cripples your opponent.", 1),
("Basher", 3, "Basher", 2, 14, "Gun bashing now does 75% more damage and has an increased chance to cripple your opponent.", 1),
("Basher", 4, "Basher", 3, 26, "Gun bashing does double damage and has an increased chance to cripple your opponent. It may also inflice a Critical Hit.", 1),
("Rooted", 1, "Strength", 9, 1, "You're part tree! While standing still, you gain +25 Damage Resistance and your melee and unarmed attacks deal 25% more damage.", 1),
("Rooted", 2, "Rooted", 1, 22, "While standing still, you now gain +50 Damage Resistance and your melee and unarmed attacks deal 50% more damage.", 1),
("Rooted", 3, "Rooted", 2, 43, "While standing still, you may automatically disarm enemies that use melee weapons against you.", 1),
("Pain Train", 1, "Strength", 10, 1, "Choo Choo! All aboard! While wearing Power Armor, sprinting into enemies hurts and staggers them. (Robots and oversized enemies are immune to the stagger.)", 1),
("Pain Train", 2, "Pain Train", 1, 24, "Sprinting into enemies while wearing Power Armor now causes severe damage and a more powerful stagger. (Robots and oversized enemies are immune to the stagger.)", 1),
("Pain Train", 3, "Pain Train", 2, 50, "Sprinting into enemies while wearing Power Armor now causes massive damage and knocks them down. Impact landing near enemies inflicts even more damage.", 1),
("Pickpocket", 1, "Perception", 1, 1, "Your quick hands and sticky fingers make picking pockets 25% easier.", 1),
("Pickpocket", 2, "Pickpocket", 1, 6, "Picking pockets is now 50% easier. You can place a live grenade in a person's inventory.", 1),
("Pickpocket", 3, "Pickpocket", 2, 17, "Picking pockets is now 75% easier, and you can steal equipped weapons.", 1),
("Pickpocket", 4, "Pickpocket", 3, 30, "Picking pockets is now twice as easy, and you can steal equipped items.", 1),
("Rifleman", 1, "Perception", 2, 1, "Keep your distance long and your kill-count high. Attacks with non-automatic rifles do 20% more damage.", 1),
("Rifleman", 2, "Rifleman", 1, 9, "Attacks with non-automatic rifles do 40% more damage and ignore 15% of a target's armor.", 1),
("Rifleman", 3, "Rifleman", 2, 18, "Attacks with non-automatic rifles do 60% more damage and ignore 20% of a target's armor.", 1),
("Rifleman", 4, "Rifleman", 3, 31, "Attacks with non-automatic rifles do 80% more damage and ignore 25% of a target's armor. They also have a slight chance of crippling a limb.", 1),
("Rifleman", 5, "Rifleman", 4, 46, "Attacks with non-automatic rifles do double damage and ignore 30% of a target's armor. They also have a slightly higher chance of crippling a limb.", 1),
("Awareness", 1, "Perception", 3, 1, "To defeat your enemies, know their weaknesses! You can view a target's specific damage resistances in V.A.T.S.", 1),
("Awareness", 2, "Awareness", 1, 14, "Knowing their weaknesses lets you attack more efficiently. 5% increase to hit chance and damage dealt to V.A.T.S. targets.", 7),
("Locksmith", 1, "Perception", 4, 1, "Your nimble fingers allow you to pick advanced locks.", 1),
("Locksmith", 2, "Locksmith", 1, 7, "You can pick Expert locks.", 1),
("Locksmith", 3, "Locksmith", 2, 18, "You can pick Master locks.", 1),
("Locksmith", 4, "Locksmith", 3, 41, "Your bobby pins never break during lockpicking.", 1),
("Demolition Expert", 1, "Perception", 5, 1, "The bigger the boom, the better! Your explosives do 25% more damage, and you can craft explosives at any chemistry station.", 1),
("Demolition Expert", 2, "Demolition Expert", 1, 10, "Your explosives do 50% more damage, and grenades gain a throwing arc.", 1),
("Demolition Expert", 3, "Demolition Expert", 2, 22, "Your explosives do 75% more damage and affect a larger area.", 1),
("Demolition Expert", 4, "Demolition Expert", 3, 34, "Your explosives now do double damage. Mines and grenades shot in V.A.T.S. explode for double damage too.", 1),
("Night Person", 1, "Perception", 6, 1, "You are a creature of the night! Gain +2 to Intelligence and Perception between the hours of 6:00 p.m. and 6:00 a.m.", 1),
("Night Person", 2, "Night Person", 1, 25, "You now have +3 to Intelligence and Perception between the hours of 6:00 p.m. and 6:00 a.m., and night vision when sneaking.", 1),
("Night Person", 3, "Night Person", 2, 37, "You have 30 extra health between the hours of 6:00 p.m. and 6:00 a.m.", 4),
("Refractor", 1, "Perception", 7, 1, "You must be part mirror! Instantly gain +10 Energy Resistance.", 1),
("Refractor", 2, "Refractor", 1, 11, "You now have +20 Energy Resistance.", 1),
("Refractor", 3, "Refractor", 2, 21, "You now have +30 Energy Resistance.", 1),
("Refractor", 4, "Refractor", 3, 35, "You now have +40 Energy Resistance.", 1),
("Refractor", 5, "Refractor", 4, 42, "You now have +50 Energy Resistance.", 1),
("Sniper", 1, "Perception", 8, 1, "It's all about focus. You have improved control and can hold your breath longer when aiming with scopes.", 1),
("Sniper", 2, "Sniper", 1, 13, "Non-automatic, scoped rifles have a 15% chance of knocking down your target.", 1),
("Sniper", 3, "Sniper", 2, 26, "Non-automatic, scoped rifles gain +25% accuracy to head shot in V.A.T.S.", 1),
("Penetrator", 1, "Perception", 9, 1, "There's no place to hide! In V.A.T.S. you can target an enemy's body parts that are blocked by cover, with a decrease in accuracy.", 1),
("Penetrator", 2, "Penetrator", 1, 28, "In V.A.T.S. when you target an enemy's body parts that are blocked by cover, there is no decrease in accuracy.", 1),
("Concentrated Fire", 1, "Perception", 10, 1, "Stay Focused! In V.A.T.S. every attack on the same body part gains +10% accuracy.", 1),
("Concentrated Fire", 2, "Concentrated Fire", 1, 26, "In V.A.T.S. every attack on the same body part gains +15% accuracy.", 1),
("Concentrated Fire", 3, "Concentrated Fire", 2, 50, "In V.A.T.S. every attack on the same body part gains +20% accuracy and does 20% more damage.", 1),
("Toughness", 1, "Endurance", 1, 1, "If nothing else, you can take a beating! Instantly gain +10 Damage Resistance.", 1),
("Toughness", 2, "Toughness", 1, 9, "You now have +20 damage resistance.", 1),
("Toughness", 3, "Toughness", 2, 18, "You now have +30 damage resistance.", 1),
("Toughness", 4, "Toughness", 3, 31, "You now have +40 damage resistance.", 1),
("Toughness", 5, "Toughness", 4, 46, "You now have +50 damage resistance.", 1),
("Lead Belly", 1, "Endurance", 2, 1, "Your digestive tract has adjusted to the weirdness of the Wasteland! Take less radiation from eating or drinking.", 1),
("Lead Belly", 2, "Lead Belly", 1, 6, "You take even less radiation from eating or drinking", 1),
("Lead Belly", 3, "Lead Belly", 2, 17, "You take no radiation from eating or drinking.", 1),
("Lifegiver", 1, "Endurance", 3, 1, "You embody wellness! Instantly gain +20 maximum Health.", 1),
("Lifegiver", 2, "Lifegiver", 1, 8, "You instantly gain another +20 maximum Health.", 1),
("Lifegiver", 3, "Lifegiver", 2, 20, "You instantly gain another +20 maximum Health and slowly regenerate lost Health.", 1),
("Chem Resistant", 1, "Endurance", 4, 1, "All the rush without the hassle! You're 50% less likely to get addicted when consuming Chems.", 1),
("Chem Resistant", 2, "Chem Resistant", 1, 22, "You gain complete immunity to chem addiction.", 1),
("Aquaboy/Aquagirl", 1, "Endurance", 5, 1, "Water is your ally. You no longer take radiation damage from swimming, and can breathe underwater.", 1),
("Aquaboy/Aquagirl", 2, "Aquaboy/Aquagirl", 1, 21, "You become totally undetectable while submerged.", 1),
("Rad Resistant", 1, "Endurance", 6, 1, "Exposure to the Wasteland has made you more resilient, instantly granting +10 Radiation Resistance.", 1),
("Rad Resistant", 2, "Rad Resistant", 1, 13, "You now have +20 Radiation Resistance.", 1),
("Rad Resistant", 3, "Rad Resistant", 2, 26, "You now have +30 Radiation Resistance.", 1),
("Rad Resistant", 4, "Rad Resistant", 3, 35, "You now hoave +40 Radiation Resistance.", 4),
("Adamantium Skeleton", 1, "Endurance", 7, 1, "Your skeleton has been infused with industructible metal, reducing limb damage by 30%", 1),
("Adamantium Skeleton", 2, "Adamantium Skeleton", 1, 13, "Your limb damage is now reduced by 60%.", 1),
("Adamantium Skeleton", 3, "Adamantium Skeleton", 2, 26, "Your limb damage is completely eliminated.", 1),
("Cannibal", 1, "Endurance", 8, 1, "Feast on mortal flesh to heal your wounds! Eating human corpses restores Health.", 1),
("Cannibal", 2, "Cannibal", 1, 19, "Eating Ghoul or Super Mutant corpses restores health.", 1),
("Cannibal", 3, "Cannibal", 2, 38, "Eating human, Ghoul, or Super Mutant corpses now restores a significant amount of Health.", 1),
("Ghoulish", 1, "Endurance", 9, 1, "Sure, you're still human - on the outside! Radiation now regenerates your lost Health.", 1),
("Ghoulish", 2, "Ghoulish", 1, 24, "Radiation now regenerates more of your lost Health.", 1),
("Ghoulish", 3, "Ghoulish", 2, 48, "Radiation now regenerates even more of your lost Health, and some Feral Ghouls will randomly become friendly.", 1),
("Ghoulish", 4, "Ghoulish", 3, 50, "Rad damage will now being to slowly heal, restoring health in the process.", 7),
("Solar Powered", 1, "Endurance", 10, 1, "Catch some rays! Gain +2 to Strength and Endurance between the hours of 6:00 a.m. and 6:00 p.m.", 1),
("Solar Powered", 2, "Solar Powered", 1, 27, "Sunlight slowly heals your radiation damage.", 1),
("Solar Powered", 3, "Solar Powered", 2, 50, "Sunlight slowly regenerates your lost Heatlh.", 1),
("Cap Collector", 1, "Charisma", 1, 1, "You've mastered the fine art of the deal! Buying and selling prices at vendors are better.", 1),
("Cap Collector", 2, "Cap Collector", 1, 20, "Buying and selling prices of vendors are now much better.", 1),
("Cap Collector", 3, "Cap Collector", 2, 41, "You can now invest a total of 500 caps to raise a store's buying capacity.", 1),
("Lady Killer/Black Widow", 1, "Charisma", 2, 1, "You're charming... and dangerous. Men/Women suffer +5% damage in combat, and are easier to persuade in dialogue.", 1),
("Lady Killer/Black Widow", 2, "Lady Killer/Black Widow", 1, 7, "Men/Women now suffer +10% damage in combat and are even easier to persuade in dialogue. They are also easier to pacify with the Intimidation perk.", 1),
("Lady Killer/Black Widow", 3, "Lady Killer/Black Widow", 2, 22, "Men/Women now suffer +15% damage in combat, and are much easier to persuade in dialogue. They are now even easier to pacity with the Intimidation perk.", 1),
("Lone Wanderer", 1, "Charisma", 3, 1, "Who needs friends anyway? When adventuring without a companion, you take 15% less damage and carry weight increases by 50.", 1),
("Lone Wanderer", 2, "Lone Wanderer", 1, 17, "When adventuring without a companion, you take 30% less damage and carry weight increases by 100.", 1),
("Lone Wanderer", 3, "Lone Wanderer", 2, 40, "When adventuring without a companion, you do 25% more damage.", 1),
("Lone Wanderer", 4, "Lone Wanderer", 3, 50, "When adventuring without a companion, you have 25 more action points.", 4),
("Attack Dog", 1, "Charisma", 4, 1, "Your faithful canine companion can hold an enemy, giving you a greater chance to hit them in V.A.T.S.", 1),
("Attack Dog", 2, "Attack Dog", 1, 9, "When your dog holds an enemy, there's a chance he'll cripple the limb he's biting.", 1),
("Attack Dog", 3, "Attack Dog", 2, 25, "When your dog holds an enemy, there's a chance he'll cause them to bleed.", 1),
("Attack Dog", 4, "Attack Dog", 3, 31, "When adventuring with your dog, you take 10% less damage.", 7),
("Animal Friend", 1, "Charisma", 5, 1, "Commune with beasts! With your gun, aim at any animal below your level and gain a chance to pacify it.", 1),
("Animal Friend", 2, "Animal Friend", 1, 12, "When you successfully pacity an animal, you can incide it to attack.", 1),
("Animal Friend", 3, "Animal Friend", 2, 28, "When you successfully pacify an animal, you can give it specific commands.", 1),
("Local Leader", 1, "Charisma", 6, 1, "As the ruler everyone turns to, you are able to establish supply lines between your workshop settlements.", 1),
("Local Leader", 2, "Local Leader", 1, 14, "You can build stores and workstations at workshop settlements.", 1),
("Party Boy/Party Girl", 1, "Charisma", 7, 1, "Nobody has a good time like you! There's no chance you'll get addicted to alcohol.", 1),
("Party Boy/Party Girl", 2, "Party Boy/Party Girl", 1, 15, "The effects of alcohol are doubled.", 1),
("Party Boy/Party Girl", 3, "Party Boy/Party Girl", 2, 37, "Your Luck is increased by 3 while you are under the influence of alcohol.", 1),
("Inspirational", 1, "Charisma", 8, 1, "Becase you lead by example, your companion does more damage in combat, and cannot hurt you.", 1),
("Inspirational", 2, "Inspirational", 1, 19, "Your companion resists more damge in combat, and can't be harmed by your attacks.", 1),
("Inspirational", 3, "Inspirational", 2, 43, "Your companion can carry more items.", 1),
("Wasteland Whisperer", 1, "Charisma", 9, 1, "Master the post-apocalypse! With your gun, aim at any Wasteland creature below your level and gain a chance to pacify it.", 1),
("Wasteland Whisperer", 2, "Wasteland Whisperer", 1, 21, "When you successfully pacity a creature, you can incide it to attack.", 1),
("Wasteland Whisperer", 3, "Wasteland Whisperer", 2, 49, "When you successfully pacity a creature, you can give it specific commands.", 1),
("Intimidation", 1, "Charisma", 10, 1, "Time to show everyone who's boss! With your gun, aim at any human opponent below your level and gain a chance to pacity them.", 1),
("Intimidation", 2, "Intimidation", 1, 23, "When you successfully pacity someone, you can incide them to attack.", 1),
("Intimidation", 3, "Intimidation", 2, 50, "When you successfully pacify someone, you can give them specific commands.", 1),
("V.A.N.S.", 1, "Intelligence", 1, 1, "Let Vault-Tec guide you! The path to your closest quest target is displayed in V.A.T.S.", 1),
("V.A.N.S.", 2, "V.A.N.S.", 1, 36, "Gain +2 to Perception.", 7),
("Medic", 1, "Intelligence", 2, 1, "Is there a doctor in the house? Stimpaks restore 40% of lost Health, and RadAway removes 40% of radiation.", 1),
("Medic", 2, "Medic", 1, 18, "Stimpaks restore 60% of lost Health, and RadAway removes 60% of radiation.", 1),
("Medic", 3, "Medic", 2, 30, "Stimpaks restore 80% of lost Health, and RadAway removes 80% of radiation.", 1),
("Medic", 4, "Medic", 3, 49, "Stimpaks and RadAway restore all lost health and radiation, and work much more quickly.", 1),
("Gun Nut", 1, "Intelligence", 3, 1, "Shoot first, kill first, with access to base level and Rank 1 gun mods.", 1),
("Gun Nut", 2, "Gun Nut", 1, 13, "You gain access to Rank 2 gun mods.", 1),
("Gun Nut", 3, "Gun Nut", 2, 25, "You gain access to Rank 3 gun mods.", 1),
("Gun Nut", 4, "Gun Nut", 3, 39, "You gain access to Rank 4 gun mods.", 1),
("Hacker", 1, "Intelligence", 4, 1, "Knowledge of cutting-edge computer encryption allows you to hack Advanced terminals.", 1),
("Hacker", 2, "Hacker", 1, 9, "You can hack Expert terminals.", 1),
("Hacker", 3, "Hacker", 2, 21, "You can hack Master terminals.", 1),
("Hacker", 4, "Hacker", 3, 33, "When hacking, you never get locked out of a terminal when things go wrong.", 1),
("Scrapper", 1, "Intelligence", 5, 1, "Waste not, want not! You can salvage uncommon components like screws, aluminum, and copper when scrapping weapons and armor.", 1),
("Scrapper", 2, "Scrapper", 1, 23, "You can salvage rare components like circuitry, nuclear material, and fiber optics when scrapping weapons and armor. Items with favorited components are highlighted.", 1),
("Scrapper", 3, "Scrapper", 2, 40, "You get more from salvaging. Appears to only apply to uncommon components, i.e. those affected by the first level of the perk.", 4),
("Science!", 1, "Intelligence", 6, 1, "Take full advantage of advanced technology with access to base level and Rank 1 high-tech mods.", 1),
("Science!", 2, "Science!", 1, 17, "You gain access to Rank 2 high-tech mods.", 1),
("Science!", 3, "Science!", 2, 28, "You gain access to Rank 3 high-tech mods.", 1),
("Science!", 4, "Science!", 3, 41, "You gain access to Rank 4 high-tech mods.", 1),
("Chemist", 1, "Intelligence", 7, "Any chems you take last 50% longer. Far out.", 1),
("Chemist", 2, "Chemist", 1, 16, "Any chems you take now last twice as long.", 1),
("Chemist", 3, "Chemist", 2, 32, "Any chems you take now last an additional 150% longer.", 1),
("Chemist", 4, "Chemist", 3, 45, "Any chems you take now last an additional 200% longer.", 1),
("Robotics Expert", 1, "Intelligence" 8, 1, "Machines will always serve humans, if you have anything to say about it. Hack a robot, and gain a chance to power it on or off, or initiate a self-destruct.", 1),
("Robotics Expert", 2, "Robotics Expert", 1, 19, "When you successfully hack a robot, you can incite it to attack.", 1),
("Robotics Expert", 3, "Robotics Expert", 2, 44, "When you successfully hack a robot, you can give it specific commands.", 1),
("Nuclear Physicist", 1, "Intelligence", 9, 1, "You've learned to split the atom...and command it. Radiation weapons do 50% more damage and Fusion Cores last an extra 25% longer.", 1),
("Nuclear Physicist", 2, "Nuclear Physicist", 1, 14, "Radiation weapons now do double damage and Fusion Cores last an extra 50% longer.", 1),
("Nuclear Physicist", 3, "Nuclear PHysicist", 2, 26, "Fusion Cores can be ejected from Power Armor like devestating grenades and Fusion Cores last twice as long.", 1),
("Nerd Rage!", 1, "Intelligence", 10, 1, "Genius. Is. ANGRY! When your Health drops below 20%, time slows and you gain +20 Damage Resistance and do 20% more damage while the effect lasts.", 1),
("Nerd Rage!", 2, "Nerd Rage!", 1, 31, "You now gain 30 more Damage Resistance and do 30% mroe damage while Nerd Rage is in effect.", 1),
("Nerd Rage!", 3, "Nerd Rage!", 2, 50, "You now gain 40 more Damage Resistance and do 40% more damage while Nerd Rage is in effect. Kills you make while enraged restore some lost Health.", 1);



