USE fo4_char_mgr_db;

INSERT INTO dlc (name)
VALUES ("Base Game"), ("Automatron"), ("Wasteland Workshop"), ("Far Harbor"), ("Contraptions Workshop"), ("Vault-Tec Workshop"), ("Nuka-World");

INSERT INTO perk (name, requirement, lvl_requirement, num_ranks, effect, granted_by, dlc_id)
VALUES ("Iron Fist - Rank 1", "Strength 1", 1, 5, "Channel your chi to unlease devestating fury! Punching attacks do 20% more damage to your opponent.", "level up", 1),
("Iron Fist - Rank 2", "Iron Fist - Rank 1", 9, 5, "Punching attacks now do 40% more damage and can disarm your opponent.", "level up", 1),
("Iron Fist - Rank 3", "Iron Fist - Rank 2", 18, 5, "Punching attacks now do 60% mroe damage. Unarmed Power Attacks have a chance to cripple one of your opponent's limbs.", "level up", 1),
("Iron Fist - Rank 4", "Iron Fist - Rank 3", 31, 5, "Punching attacks now do 80% more damage. Unarmed Power Attacks have an increased chance to cripple one of your opponent's limbs.", "level up", 1),
("Iron Fist - Rank 5", "Iron Fist - Rank 4", 46, 5, "Punching attacks now do double damage. Criticals in V.A.T.S. will paralyze your opponent.", "level up", 1),
("Big Leagues - Rank 1", "Strength 2", 1, 5, "Swing for the fences! Do 20% more melee weapon damage.", "level up", 1),
("Big Leagues - Rank 2", "Big Leagues - Rank 1", 7, 5, "You now do 40% more melee weapon damage and gain a chance to disarm your opponent.", "level up", 1),
("Big Leagues - Rank 3", "Big Leagues - Rank 2", 15, 5, "You now do 60% more melee weapon damage and gain an increased chance to disarm your opponent.", "level up", 1),
("Big Leagues - Rank 4", "Big Leagues - Rank 3", 27, 5, "You now do 80% more melee weapon damage and hit all targets in front of you.", "level up", 1),
("Big Leagues - Rank 5", "Big Leagues - Rank 4", 42, 5, "You now do double damage with a melee weapon, and gain a chance to cripple your opponent, or grand slam their head clean off!", "level up", 1),
("Armorer - Rank 1", "Strength 3", 1, 4, "Protect yourself from the dangers of the Wasteland with access to base level and Rank 1 armor mods.", "level up", 1),
("Armorer - Rank 2", "Armorer - Rank 1", 13, 4, "You gain access to Rank 2 armor mods.", "level up", 1),
("Armorer - Rank 3", "Armorer - Rank 2", 25, 4, "You gain access to Rank 3 armor mods.", "level up", 1),
("Armorer - Rank 4", "Armorer - Rank 3", 39, 4, "You gain access to Rank 4 armor mods.", "level up", 1),
("Blacksmith - Rank 1", "Strength 4", 1, 3, "Fire up the forge and gain access to base level and Rank 1 melee weapon mods.", "level up", 1),
("Blacksmith - Rank 2", "Blacksmith - Rank 1", 16, 3, "You gain access to Rank 2 melee weapon mods.", "level up", 1),
("Blacksmith - Rank 3", "Blacksmith - Rank 2", 29, 3, "You gain access to Rank 3 melee weapon mods.", "level up", 1),
("Heavy Gunner - Rank 1", "Strength 5", 1, 5, "Thanks to practice and conditioning, heavy guns do 20% more damage.", "level up", 1),
("Heavy Gunner - Rank 2", "Heavy Gunner - Rank 1", 11, 5, "Heavy guns now do 40% more damage, and have improved hip fire accuracy.", "level up", 1),
("Heavy Gunner - Rank 3", "Heavy Gunner - Rank 2", 21, 5, "Heavy guns now do 60% more damage. Hip fire accuracy is increased even more.", "level up", 1),
("Heavy Gunner - Rank 4", "Heavy Gunner - Rank 3", 35, 5, "Heavy guns now do 80% more damage and have a chance to stagger your opponent.", "level up", 1),
("Heavy Gunner - Rank 5", "Heavy Gunner - Rank 4", 47, 5, "Heavy guns now do double damage.", "level up", 1),
("Strong Back - Rank 1", "Strength 6", 1, 5, "What are you, part pack mule? Gain +25 to carry weight.", "level up", 1),
("Strong Back - Rank 2", "Strong Back - Rank 1", 10, 5, "You now have +50 to carry weight.", "level up", 1),
("Strong Back - Rank 3", "Strong Back - Rank 2", 20, 5, "When overencumbered, you can use Action Points to run.", "level up", 1),
("Strong Back - Rank 4", "Strong Back - Rank 3", 30, 5, "When overencumbered, you can fast travel.", "level up", 1),
("Strong Back - Rank 5", "Strong Back - Rank 4", 40, 5, "When overencumbered, running costs 50% less action points.", "level up", 4),
("Steady Aim - Rank 1", "Strength 7", 1, 3, "Stay on target! Hip-fire accuracy is improved when firing any gun.", "level up", 1),
("Steady Aim - Rank 2", "Steady Aim - Rank 1", 28, 3, "Hip-fire accuracy is improved even more when firing any gun.", "level up", 1),
("Steady Aim - Rank 3", "Steady Aim - Rank 2", 49, 3, "Hip-fire damage is improved when firing any gun.", "level up", 7),
("Basher - Rank 1", "Strength 8", 1, 4, "Get up close and personal! Gun bashing does 25% mroe damage.", "level up", 1),
("Basher - Rank 2", "Basher - Rank 1", 5, 4, "Gun bashing now does 50% more damage and possibly cripples your opponent.", "level up", 1),
("Basher - Rank 3", "Basher - Rank 2", 14, 4, "Gun bashing now does 75% more damage and has an increased chance to cripple your opponent.", "level up", 1),
("Basher - Rank 4", "Basher - Rank 3", 26, 4, "Gun bashing does double damage and has an increased chance to cripple your opponent. It may also inflice a Critical Hit.", "level up", 1),
("Rooted - Rank 1", "Strength 9", 1, 3, "You're part tree! While standing still, you gain +25 Damage Resistance and your melee and unarmed attacks deal 25% more damage.", "level up", 1),
("Rooted - Rank 2", "Rooted - Rank 1", 22, 3, "While standing still, you now gain +50 Damage Resistance and your melee and unarmed attacks deal 50% more damage.", "level up", 1),
("Rooted - Rank 3", "Rooted - Rank 2", 43, 3, "While standing still, you may automatically disarm enemies that use melee weapons against you.", "level up", 1),
("Pain Train - Rank 1", "Strength 10", 1, 3, "Choo Choo! All aboard! While wearing Power Armor, sprinting into enemies hurts and staggers them. (Robots and oversized enemies are immune to the stagger.)", "level up", 1),
("Pain Train - Rank 2", "Pain Train - Rank 1", 24, 3, "Sprinting into enemies while wearing Power Armor now causes severe damage and a more powerful stagger. (Robots and oversized enemies are immune to the stagger.)", "level up", 1),
("Pain Train - Rank 3", "Pain Train - Rank 2", 50, 3, "Sprinting into enemies while wearing Power Armor now causes massive damage and knocks them down. Impact landing near enemies inflicts even more damage.", "level up", 1),
("Pickpocket - Rank 1", "Perception 1", 1, 4, "Your quick hands and sticky fingers make picking pockets 25% easier.", "level up", 1),
("Pickpocket - Rank 2", "Pickpocket - Rank 1", 6, 4, "Picking pockets is now 50% easier. You can place a live grenade in a person's inventory.", "level up", 1),
("Pickpocket - Rank 3", "Pickpocket - Rank 2", 17, 4, "Picking pockets is now 75% easier, and you can steal equipped weapons.", "level up", 1),
("Pickpocket - Rank 4", "Pickpocket - Rank 3", 30, 4, "Picking pockets is now twice as easy, and you can steal equipped items.", "level up", 1),
("Rifleman - Rank 1", "Perception 2", 1, 5, "Keep your distance long and your kill-count high. Attacks with non-automatic rifles do 20% more damage.", "level up", 1),
("Rifleman - Rank 2", "Rifleman - Rank 1", 9, 5, "Attacks with non-automatic rifles do 40% more damage and ignore 15% of a target's armor.", "level up", 1),
("Rifleman - Rank 3", "Rifleman - Rank 2", 18, 5, "Attacks with non-automatic rifles do 60% more damage and ignore 20% of a target's armor.", "level up", 1),
("Rifleman - Rank 4", "Rifleman - Rank 3", 31, 5, "Attacks with non-automatic rifles do 80% more damage and ignore 25% of a target's armor. They also have a slight chance of crippling a limb.", "level up", 1),
("Rifleman - Rank 5", "Rifleman - Rank 4", 46, 5, "Attacks with non-automatic rifles do double damage and ignore 30% of a target's armor. They also have a slightly higher chance of crippling a limb.", "level up", 1),
("Awareness - Rank 1", "Perception 3", 1, 2, "To defeat your enemies, know their weaknesses! You can view a target's specific damage resistances in V.A.T.S.", "level up", 1),
("Awareness - Rank 2", "Awareness - Rank 1", 14, 2, "Knowing their weaknesses lets you attack more efficiently. 5% increase to hit chance and damage dealt to V.A.T.S. targets.", "level up", 7),
("Locksmith - Rank 1", "Perception 4", 1, 4, "Your nimble fingers allow you to pick advanced locks.", "level up", 1),
("Locksmith - Rank 2", "Locksmith - Rank 1", 7, 4, "You can pick Expert locks.", "level up", 1),
("Locksmith - Rank 3", "Locksmith - Rank 2", 18, 4, "You can pick Master locks.", "level up", 1),
("Locksmith - Rank 4", "Locksmith - Rank 3", 41, 4, "Your bobby pins never break during lockpicking.", "level up", 1),
("Demolition Expert - Rank 1", "Perception 5", 1, 4, "The bigger the boom, the better! Your explosives do 25% more damage, and you can craft explosives at any chemistry station.", "level up", 1),
("Demolition Expert - Rank 2", "Demolition Expert - Rank 1", 10, 4, "Your explosives do 50% more damage, and grenades gain a throwing arc.", "level up", 1),
("Demolition Expert - Rank 3", "Demolition Expert - Rank 2", 22, 4, "Your explosives do 75% more damage and affect a larger area.", "level up", 1),
("Demolition Expert - Rank 4", "Demolition Expert - Rank 3", 34, 4, "Your explosives now do double damage. Mines and grenades shot in V.A.T.S. explode for double damage too.", "level up", 1),
("Night Person - Rank 1", "Perception 6", 1, 3, "You are a creature of the night! Gain +2 to Intelligence and Perception between the hours of 6:00 p.m. and 6:00 a.m.", "level up", 1),
("Night Person - Rank 2", "Night Person - Rank 1", 25, 3, "You now have +3 to Intelligence and Perception between the hours of 6:00 p.m. and 6:00 a.m., and night vision when sneaking.", "level up", 1),
("Night Person - Rank 3", "Night Person - Rank 2", 37, 3, "You have 30 extra health between the hours of 6:00 p.m. and 6:00 a.m.", "level up", 4),
("Refractor - Rank 1", "Perception 7", 1, 5, "You must be part mirror! Instantly gain +10 Energy Resistance.", "level up", 1),
("Refractor - Rank 2", "Refractor - Rank 1", 11, 5, "You now have +20 Energy Resistance.", "level up", 1),
("Refractor - Rank 3", "Refractor - Rank 2", 21, 5, "You now have +30 Energy Resistance.", "level up", 1),
("Refractor - Rank 4", "Refractor - Rank 3", 35, 5, "You now have +40 Energy Resistance.", "level up", 1),
("Refractor - Rank 5", "Refractor - Rank 4", 42, 5, "You now have +50 Energy Resistance.", "level up", 1),
("Sniper - Rank 1", "Perception 8", 1, 3, "It's all about focus. You have improved control and can hold your breath longer when aiming with scopes.", "level up", 1),
("Sniper - Rank 2", "Sniper - Rank 1", 13, 3, "Non-automatic, scoped rifles have a 15% chance of knocking down your target.", "level up", 1),
("Sniper - Rank 3", "Sniper - Rank 2", 26, 3, "Non-automatic, scoped rifles gain +25% accuracy to head shot in V.A.T.S.", "level up", 1),
("Penetrator - Rank 1", "Perception 9", 1, 2, "There's no place to hide! In V.A.T.S. you can target an enemy's body parts that are blocked by cover, with a decrease in accuracy.", "level up", 1),
("Penetrator- Rank 2", "Penetrator - Rank 1", 28, 2, "In V.A.T.S. when you target an enemy's body parts that are blocked by cover, there is no decrease in accuracy.", "level up", 1),
("Concentrated Fire - Rank 1", "Perception 10", 1, 3, "Stay Focused! In V.A.T.S. every attack on the same body part gains +10% accuracy.", "level up", 1),
("Concentrated Fire - Rank 2", "Concentrated Fire - Rank 1", 26, 3, "In V.A.T.S. every attack on the same body part gains +15% accuracy.", "level up", 1),
("Concentrated Fire - Rank 3", "Concentrated Fire - Rank 2", 50, 3, "In V.A.T.S. every attack on the same body part gains +20% accuracy and does 20% more damage.", "level up", 1);

